- name: unpack grafana-agent to /usr/local/bin
  ansible.builtin.unarchive:
    src: https://github.com/grafana/agent/releases/download/v{{ agent_version }}/agent-freebsd-amd64.zip
    dest: /usr/local/bin
    mode: '0755'
    remote_src: yes
