---
# tasks file for grafana-agent

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: true
  delegate_to: localhost

- name: Install on RedHat
  ansible.builtin.include_tasks: "RedHat.yml"
  when:
    - ansible_os_family == "RedHat"

- name: Install on Debian
  ansible.builtin.include_tasks: "Debian.yml"
  when:
    - ansible_os_family == "Debian"

- name: Install on FreeBSD
  ansible.builtin.include_tasks: "FreeBSD.yml"
  when:
    - ansible_os_family == "FreeBSD"

- name: Configure grafana-agent on RedHat or Debian based systems
  ansible.builtin.include_tasks: "configure_linux.yml"
  when:
    - ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: Configure grafana-agent on FreeBSD based systems
  ansible.builtin.include_tasks: "configure_FreeBSD.yml"
  when:
    - ansible_os_family == "FreeBSD"
