---
- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: true
  delegate_to: localhost

- name: Add grafana repository
  ansible.builtin.yum_repository:
    name: grafana
    description: grafana
    baseurl: https://rpm.grafana.com
    gpgkey: https://rpm.grafana.com/gpg.key
    gpgcheck: true

- name: Install grafana-agent
  ansible.builtin.package:
    name: grafana-agent
    state: present

- name: Configure grafana-agent
  ansible.builtin.copy:
    content: >-
      {{
        grafana_agent_default_config |
        combine(grafana_agent_config, recursive=True) |
        to_nice_yaml(indent=2, explicit_start=True, explicit_end=True)
      }}
    dest: /etc/grafana-agent.yaml
    owner: root
    group: grafana-agent
    mode: 0644
  notify:
    - Restart grafana-agent

- name: Configure grafana-agent addresses
  ansible.builtin.template:
    src: sysconfig/grafana-agent.j2
    dest: /etc/sysconfig/grafana-agent
    owner: root
    group: grafana-agent
    mode: 0644
  notify:
    - Restart grafana-agent
