---
- name: Add grafana repository
  ansible.builtin.yum_repository:
    name: grafana
    description: grafana
    baseurl: https://rpm.grafana.com
    gpgkey: https://rpm.grafana.com/gpg.key
    gpgcheck: true

- name: Install grafana-agent
  ansible.builtin.package:
    name: grafana-agent
    state: present

- name: Create grafana_agent_wal_directory
  ansible.builtin.file:
    name: "{{ grafana_agent_wal_directory }}"
    state: directory
    owner: grafana_agent
    group: grafana_agent
    mode: 0700
  notify:
    - Restart grafana-agent

- name: Create grafana_agent_positions_directory
  ansible.builtin.file:
    name: "{{ grafana_agent_positions_directory }}"
    state: directory
    owner: grafana_agent
    group: grafana_agent
    mode: 0700
  notify:
    - Restart grafana-agent

- name: Configure grafana-agent
  ansible.builtin.copy:
    content: >-
      {{
        grafana_agent_combined_config |
        to_nice_yaml(indent=2, explicit_start=True, explicit_end=True)
      }}
    dest: /etc/grafana-agent.yaml
    owner: root
    group: grafana-agent
    mode: 0644
  notify:
    - Restart grafana-agent

- name: Configure grafana-agent addresses
  ansible.builtin.template:
    src: sysconfig/grafana-agent.j2
    dest: /etc/sysconfig/grafana-agent
    owner: root
    group: grafana-agent
    mode: 0644
  notify:
    - Restart grafana-agent
